import { MenuItem } from '@/types'

export const menuItems: MenuItem[] = [
  // HOT DRINKS
  {
    id: 'h1',
    name: 'Signature Espresso',
    description: 'Our house-roasted single-origin beans, pulled to perfection with a velvety crema.',
    price: 3.50,
    category: 'hot',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&q=80',
    tags: ['espresso', 'classic', 'bold'],
    popular: true,
    calories: 10,
  },
  {
    id: 'h2',
    name: 'Velvet Flat White',
    description: 'Microfoam steamed milk over a double ristretto. Silky, rich, and deeply satisfying.',
    price: 5.00,
    category: 'hot',
    image: 'https://images.unsplash.com/photo-1611564494260-6f21b80af7ea?w=600&q=80',
    tags: ['milk', 'espresso', 'smooth'],
    popular: true,
    calories: 120,
  },
  {
    id: 'h3',
    name: 'Cardamom Latte',
    description: 'Aromatic cardamom-spiced latte with steamed oat milk and a dusting of cinnamon.',
    price: 5.50,
    category: 'hot',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    tags: ['spiced', 'oat milk', 'aromatic'],
    calories: 180,
  },
  {
    id: 'h4',
    name: 'Black Americano',
    description: 'Espresso with hot water — clean, bold, and unapologetically simple.',
    price: 3.75,
    category: 'hot',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80',
    tags: ['black', 'classic', 'bold'],
    calories: 15,
  },
  {
    id: 'h5',
    name: 'Honey Rose Cortado',
    description: 'Equal parts espresso and warm milk, infused with rose water and raw honey.',
    price: 5.75,
    category: 'hot',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80',
    tags: ['floral', 'honey', 'special'],
    popular: true,
    calories: 95,
  },
  {
    id: 'h6',
    name: 'Matcha Ceremonial',
    description: 'Ceremonial grade Japanese matcha whisked with steamed almond milk and agave.',
    price: 6.00,
    category: 'hot',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80',
    tags: ['matcha', 'japanese', 'earthy'],
    calories: 140,
  },

  // COLD DRINKS
  {
    id: 'c1',
    name: 'Cold Brew Reserve',
    description: '24-hour slow-steeped cold brew concentrate over glacier ice. Smooth and potent.',
    price: 5.50,
    category: 'cold',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80',
    tags: ['cold brew', 'strong', 'smooth'],
    popular: true,
    calories: 20,
  },
  {
    id: 'c2',
    name: 'Nitro Cloud',
    description: 'Nitrogen-infused cold brew with a cascading foam head. Like coffee on velvet.',
    price: 6.50,
    category: 'cold',
    image: 'https://images.unsplash.com/photo-1568649929103-28ffbefaca1e?w=600&q=80',
    tags: ['nitro', 'smooth', 'creamy'],
    popular: true,
    calories: 30,
  },
  {
    id: 'c3',
    name: 'Iced Caramel Macchiato',
    description: 'Vanilla-sweetened milk, cold espresso shots, and artisan caramel drizzle.',
    price: 6.00,
    category: 'cold',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&q=80',
    tags: ['caramel', 'sweet', 'iced'],
    calories: 250,
  },
  {
    id: 'c4',
    name: 'Hibiscus Fizz',
    description: 'House-brewed hibiscus tea with sparkling water, lime, and a pinch of sea salt.',
    price: 4.75,
    category: 'cold',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80',
    tags: ['floral', 'sparkling', 'refreshing'],
    calories: 60,
  },
  {
    id: 'c5',
    name: 'Mango Yuzu Lemonade',
    description: 'Tropical mango puree, Japanese yuzu citrus, cold-pressed lemon. Sunshine in a glass.',
    price: 5.25,
    category: 'cold',
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&q=80',
    tags: ['tropical', 'citrus', 'fruity'],
    popular: true,
    calories: 140,
  },
  {
    id: 'c6',
    name: 'Lavender Cold Brew',
    description: 'Our cold brew steeped with dried lavender blossoms and finished with sweet cream.',
    price: 6.25,
    category: 'cold',
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&q=80',
    tags: ['lavender', 'floral', 'sweet'],
    calories: 110,
  },

  // SHAKES
  {
    id: 's1',
    name: 'Dark Mocha Shake',
    description: 'Intense 70% dark chocolate, cold brew espresso, and house-made vanilla bean ice cream.',
    price: 8.50,
    category: 'shakes',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80',
    tags: ['chocolate', 'espresso', 'indulgent'],
    popular: true,
    calories: 520,
  },
  {
    id: 's2',
    name: 'Salted Caramel Dream',
    description: 'Burnt caramel, Himalayan salt, vanilla gelato, blended to cloud-like perfection.',
    price: 8.00,
    category: 'shakes',
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80',
    tags: ['caramel', 'salted', 'creamy'],
    popular: true,
    calories: 580,
  },
  {
    id: 's3',
    name: 'Matcha Mint Cooler',
    description: 'Ceremonial matcha, fresh mint, coconut milk, and honey. Cool, calm, caffeinated.',
    price: 7.50,
    category: 'shakes',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    tags: ['matcha', 'mint', 'coconut'],
    calories: 320,
  },
  {
    id: 's4',
    name: 'Berry Bliss Blend',
    description: 'Strawberry, blueberry, raspberry, acai, and banana with almond milk. A nutrient bomb.',
    price: 7.75,
    category: 'shakes',
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600&q=80',
    tags: ['berries', 'healthy', 'fruity'],
    calories: 290,
  },
  {
    id: 's5',
    name: 'Peanut Butter Espresso',
    description: 'Natural peanut butter, banana, two espresso shots, oat milk. The ultimate pick-me-up.',
    price: 9.00,
    category: 'shakes',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80',
    tags: ['peanut butter', 'espresso', 'protein'],
    calories: 450,
  },
  {
    id: 's6',
    name: 'White Chocolate Truffle',
    description: 'Belgian white chocolate, vanilla bean, heavy cream, and a toasted coconut rim.',
    price: 8.75,
    category: 'shakes',
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600&q=80',
    tags: ['white chocolate', 'coconut', 'luxury'],
    calories: 610,
  },

  // SPECIALS
  {
    id: 'sp1',
    name: 'Seasonal Saffron Latte',
    description: 'Persian saffron, cardamom, and rose water in steamed whole milk. A poet\'s drink.',
    price: 7.50,
    category: 'specials',
    image: 'https://images.unsplash.com/photo-1607877742574-a7d9a7449af3?w=600&q=80',
    tags: ['saffron', 'seasonal', 'exotic'],
    popular: true,
    calories: 200,
  },
  {
    id: 'sp2',
    name: 'Charcoal Lemonade',
    description: 'Activated charcoal, cold-pressed lemon, ginger, and raw honey. Detox never looked so dark.',
    price: 6.50,
    category: 'specials',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80',
    tags: ['charcoal', 'detox', 'trendy'],
    calories: 80,
  },
]

export const categories = [
  { id: 'all', label: 'All Drinks' },
  { id: 'hot', label: 'Hot Drinks' },
  { id: 'cold', label: 'Cold Drinks' },
  { id: 'shakes', label: 'Shakes' },
  { id: 'specials', label: 'Specials' },
]
